# Generated by Django 4.1.2 on 2022-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_city_person_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Credit',
            field=models.BooleanField(default=False, verbose_name='Credit Card'),
        ),
        migrations.AddField(
            model_name='person',
            name='Debit',
            field=models.BooleanField(default=False, verbose_name='Debit Card'),
        ),
        migrations.AddField(
            model_name='person',
            name='Passbook',
            field=models.BooleanField(default=True, verbose_name='Passbook'),
        ),
    ]
