# Generated by Django 4.1.2 on 2022-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_person_credit_person_debit_person_passbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Materials_Provide',
            field=models.BooleanField(default=True, null=True, verbose_name='Materials Required:'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Passbook',
            field=models.BooleanField(default=False, verbose_name='Passbook'),
        ),
    ]
